### ISSUE TITLE
Link to the Helm chart is broken

### ISSUE THREAD

**Issue by Onlinehead** [ytsaurus/yt-k8s-operator#1]
Hi,
Just found that the link to the operator Helm chart:
https://github.com/ytsaurus/yt-k8s-operator/blob/ed7a11096472dc7c92c5430bad9114e5175fd394/README.md?plain=1#L15
forwards to the Dockerhub and require authorization, so it is probably not a helm chart nor something which is available at all.

**Comment by savnadya** [comment]
Hello! Thank you for the issue. It was fixed here: 14675254e1ff902b5401cea726c88e241ea96770
