### ISSUE TITLE
Use backend for heavy operations 

### ISSUE THREAD

**Issue by kozubaeff** [ytsaurus/yt-k8s-operator#256]
Currently, for heavy operations (read_table, get_job_stderr) UI directly uses proxies. There should be an option for the UI to use a backend for it. UI has a [flag](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/src/shared/ui-settings.ts#L15) for  situations when proxies are not open for external use (inside of k8s network as an example)

**Comment by sgburtsev** [comment]
+1 for this change. I made almost identical changes for the same reason:
```go
type UISettings struct {
	DirectDownload bool `yson:"directDownload"`
}
type UICustom struct {
	OdinBaseUrl *string    `yson:"odinBaseUrl,omitempty"`
	UISettings  UISettings `yson:"uiSettings"`
}
```
