### ISSUE TITLE
Ytop-chart-controller crashes

### ISSUE THREAD

**Issue by oartemev** [ytsaurus/yt-k8s-operator#36]
The pod `ytsaurus-ytop-chart-controller-manager` is in the infinite CrashLoopBackOff state.

The used configuration:
* ytop-chart v 0.4.0
* coreImage: ytsaurus/ytsaurus:stable-23.1.0-relwithdebinfo

The log is attached.
[chart_fail.log](https://github.com/ytsaurus/yt-k8s-operator/files/12788881/chart_fail.log)

**Comment by chizhonkova** [comment]
Hi! This bug was fixed in v0.4.1 (in https://github.com/ytsaurus/yt-k8s-operator/commit/c097c9ae65ad24c04ea4142f751a287ad08aec89).

**Comment by oartemev** [comment]
Checked - it works, thanks.
